[Settings]
Current Profile = PST
Default Open Single = true
Use Normal Spell Scriptnames = false
Use Grid Lines = false
Display Extra Creature Info = false
Ignore Data Versions = false
Allow Quicksave Editing = true
Large Appearance Colour Icons = false
Round Appearance Colour Icons = false
Max HP On Level Up = true
First Roll HP = true

[Item Browser Window]
Window State = 1
Window Flags = 0
Left = 75
Right = 1259
Top = 61
Bottom = 1009
Add Full Stacks = 1009

[Save Editor Window]
Window State = 1
Window Flags = 0
Left = 11
Right = 1313
Top = 64
Bottom = 805

[Editor Window]
x = 276
y = 150
width = 1383
height = 1251

# Window State has four possible settings:- 0=Hidden (avoid using 0, it won't appear in the taskbar), 1=Normal, 2=Minimised, 3=Maximised.
Window State = 1

[Spell Browser Window]
Window State = 1
Window Flags = 0
Left = 232
Right = 1346
Top = 63
Bottom = 987

[BG]
Install Path = Z:\home\ufo\Temp\Games\Baldur's Gate - Enhanced Edition\
Language = 
Save Directory = Z:\home\ufo\Temp\Games\Baldur's Gate - Enhanced Edition\wineprefix\drive_c\users\ufo\Documents\Baldur's Gate - Enhanced Edition\
Custom Save Directory = false

[BG2]
Install Path = Z:\home\ufo\Temp\Games\Baldur's Gate 2 - Enhanced Edition\
Language = 
Save Directory = Z:\home\ufo\Temp\Games\Baldur's Gate 2 - Enhanced Edition\wineprefix\drive_c\users\ufo\Documents\Baldur's Gate II - Enhanced Edition\
Custom Save Directory = false

[Character Browser Window]
Window State = 1
Window Flags = 0
Left = 301
Right = 776
Top = 39
Bottom = 389

[Creature Browser Window]
Window State = 1
Window Flags = 0
Left = 825
Right = 1650
Top = 0
Bottom = 544

[IWD]
Install Path = Z:\home\ufo\Temp\Games\Icewind Dale - Enhanced Edition\
Language = 
Save Directory = Z:\home\ufo\Temp\Games\Icewind Dale - Enhanced Edition\wineprefix\drive_c\users\ufo\Documents\Icewind Dale - Enhanced Edition\
Custom Save Directory = false

[PST]
Install Path = Z:\home\ufo\Temp\Games\Planescape Torment - Enhanced Edition\
Language = 
Save Directory = Z:\home\ufo\Temp\Games\Planescape Torment - Enhanced Edition\wineprefix\drive_c\users\ufo\Documents\Planescape Torment - Enhanced Edition\
Custom Save Directory = false
