//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BGEdit.rc
//
#define IDC_VERIFY                      3
#define IDD_ABOUTBOX                    100
#define IDD_BGEDIT_FORM                 101
#define IDR_MAINFRAME                   128
#define IDR_BGEDITTYPE                  129
#define IDD_OPEN_GAME                   132
#define IDD_GAME_LOCATION               134
#define IDD_ITEMS                       149
#define IDD_SPELLS                      150
#define IDD_MAGIC                       151
#define IDB_ARROW_UP                    152
#define IDB_ARROW_DOWN                  153
#define IDD_PROFICIENCIES               153
#define IDD_MAGIC_MEMORIZE              154
#define IDD_CHARACTERISTICS             155
#define IDD_SAVINGTHROWS                156
#define IDD_DUAL_LEVEL                  157
#define IDD_THIEF_SKILLS                158
#define IDI_ICON1                       159
#define IDD_LOCATION                    161
#define IDD_OPEN_CHARACTER              162
#define IDD_APPEARANCE                  163
#define IDD_MISC_ABILITIES              164
#define IDD_CHANGE_NAME                 165
#define IDC_GAME_PATH                   1003
#define IDC_BROWSE_LOCATION             1004
#define IDC_SAVED_GAMES                 1005
#define IDC_GAMETYPE                    1006
#define IDC_GAMETYPE2                   1007
#define IDC_CHAR1                       1009
#define IDC_CHAR2                       1011
#define IDC_CHAR3                       1012
#define IDC_CHAR4                       1013
#define IDC_CHAR5                       1014
#define IDC_CHAR6                       1015
#define IDC_STR                         1017
#define IDC_DEX                         1018
#define IDC_STR_BONUS                   1019
#define IDC_SPIN_STR                    1020
#define IDC_SPIN_DEX                    1021
#define IDC_SPIN_STR_BONUS              1022
#define IDC_CON                         1023
#define IDC_SPIN_CON                    1024
#define IDC_INT                         1025
#define IDC_SPIN_INT                    1026
#define IDC_WIS                         1027
#define IDC_SPIN_WIS                    1028
#define IDC_CHA                         1029
#define IDC_SPIN_CHA                    1030
#define IDC_PROF_LGSWORD                1031
#define IDC_PROF_SMSWORD                1032
#define IDC_PROF_BOW                    1033
#define IDC_PROF_SPEAR                  1034
#define IDC_INVENTORY                   1035
#define IDC_MAX_QTY                     1036
#define IDC_DELETEITEM                  1037
#define IDC_ITEMS                       1037
#define IDC_EDITITEM                    1038
#define IDC_VIEW_ARMOR                  1038
#define IDC_VIEW_WEAPONS                1039
#define IDC_PROF_BLUNT                  1039
#define IDC_VIEW_HELMS                  1040
#define IDC_PROF_SPIKED                 1040
#define IDC_VIEW_AMULETS                1041
#define IDC_PROF_AXE                    1041
#define IDC_VIEW_MISSILES               1042
#define IDC_PROF_MISSILE                1042
#define IDC_VIEW_BELTS                  1043
#define IDC_SPIN_PROF_LGSWORD           1043
#define IDC_VIEW_RINGS                  1044
#define IDC_SPIN_PROF_SMSWORD           1044
#define IDC_VIEW_SHIELDS                1045
#define IDC_SPIN_PROF_BOW               1045
#define IDC_VIEW_BOOTS                  1046
#define IDC_SPIN_PROF_SPEAR             1046
#define IDC_VIEW_CLOAKS                 1047
#define IDC_SPIN_PROF_BLUNT             1047
#define IDC_VIEW_GAUNTLETS              1048
#define IDC_SPIN_PROF_SPIKED            1048
#define IDC_VIEW_POTIONS                1049
#define IDC_SPIN_PROF_AXE               1049
#define IDC_VIEW_WANDS                  1050
#define IDC_SPIN_PROF_MISSILE           1050
#define IDC_VIEW_BOOKS                  1051
#define IDC_VIEW_SCROLLS                1052
#define IDC_VIEW_MISC                   1053
#define IDC_ALL                         1055
#define IDC_NONE                        1056
#define IDC_CURRENT_ITEM                1057
#define IDC_QTY                         1058
#define IDC_EXP                         1060
#define IDC_HP_BASE                     1061
#define IDC_GOLD                        1063
#define IDC_SPELLS                      1066
#define IDC_SEPLL_INNATE                1070
#define IDC_SPELL_PRIEST                1071
#define IDC_SPELL_WIZARD                1072
#define IDC_CURRENT_SPELL               1073
#define IDC_TIMES_MEMORIZED             1074
#define IDC_MAGIC_TYPE                  1075
#define IDC_MAGIC_LEVEL                 1077
#define IDC_CAN_MEMORIZE                1078
#define IDC_MEMORIZED                   1079
#define IDC_AVAILABLE                   1080
#define IDC_KNOWN                       1081
#define IDC_ADD_TO_KNOWN                1082
#define IDC_REMOVE_FROM_KNOWN           1083
#define IDC_EDIT_MAGIC                  1083
#define IDC_EDIT_PROFICIENCIES          1084
#define IDC_MEM_TIMES                   1085
#define IDC_EDIT_CHARACTERISTICS        1085
#define IDC_SEX                         1086
#define IDC_EDIT_SAVES                  1086
#define IDC_ALIGNMENT                   1087
#define IDC_SAVE_PPD                    1087
#define IDC_EDIT_THIEF                  1087
#define IDC_RACE                        1088
#define IDC_SPIN_PPD                    1088
#define IDC_EDIT_DUAL                   1088
#define IDC_CLASS                       1089
#define IDC_SAVE_RSW                    1089
#define IDC_FIRST_LEVEL                 1089
#define IDC_EDIT_LOCATION               1089
#define IDC_SPIN_RSW                    1090
#define IDC_PICK_POCKETS                1090
#define IDC_MAGE_SPECIALTY              1090
#define IDC_EDIT_APPEARANCE             1090
#define IDC_SAVE_PP                     1091
#define IDC_OPEN_LOCKS                  1091
#define IDC_EDIT_MISC_ABILITIES         1091
#define IDC_SPIN_PP                     1092
#define IDC_DETECT_TRAPS                1092
#define IDC_SAVE_BW                     1093
#define IDC_STEALTH                     1093
#define IDC_SPIN_BW                     1094
#define IDC_SPIN_PICK_POCKETS           1094
#define IDC_SAVE_S                      1095
#define IDC_PICK_POCKETS_BASE           1095
#define IDC_SPIN_S                      1096
#define IDC_PICK_POCKETS_RACE           1096
#define IDC_AREA                        1096
#define IDC_PICK_POCKETS_DEX            1097
#define IDC_LOCATION                    1097
#define IDC_PICK_POCKETS_ACTUAL         1098
#define IDC_QUAD_A1                     1098
#define IDC_OPEN_LOCKS_BASE             1099
#define IDC_QUAD_A2                     1099
#define IDC_OPEN_LOCKS_RACE             1100
#define IDC_QUAD_A3                     1100
#define IDC_OPEN_LOCKS_DEX              1101
#define IDC_QUAD_A4                     1101
#define IDC_OPEN_LOCKS_ACTUAL           1102
#define IDC_QUAD_B1                     1102
#define IDC_DETECT_TRAPS_BASE           1103
#define IDC_QUAD_B2                     1103
#define IDC_DETECT_TRAPS_RACE           1104
#define IDC_QUAD_B3                     1104
#define IDC_DETECT_TRAPS_DEX            1105
#define IDC_QUAD_B4                     1105
#define IDC_DETECT_TRAPS_ACTUAL         1106
#define IDC_QUAD_C1                     1106
#define IDC_STEALTH_BASE                1107
#define IDC_QUAD_C2                     1107
#define IDC_STEALTH_RACE                1108
#define IDC_QUAD_C3                     1108
#define IDC_STEALTH_DEX                 1109
#define IDC_QUAD_C4                     1109
#define IDC_STEALTH_ACTUAL              1110
#define IDC_QUAD_D1                     1110
#define IDC_SPIN_OPEN_LOCKS             1111
#define IDC_QUAD_D2                     1111
#define IDC_SPIN_DETECT_TRAPS           1112
#define IDC_QUAD_D3                     1112
#define IDC_SPIN_STEALTH                1113
#define IDC_QUAD_D4                     1113
#define IDC_CHARACTERS                  1116
#define IDC_SET_MEM                     1117
#define IDC_AVATAR_RACE                 1119
#define IDC_AVATAR_GENDER               1120
#define IDC_AVATAR_CLASS                1121
#define IDC_RACIAL_ENEMY                1123
#define IDC_THAC0                       1124
#define IDC_SPIN_THAC0                  1125
#define IDC_NUMBER_OF_ATTACKS           1126
#define IDC_AC                          1127
#define IDC_NAME                        1127
#define IDC_SPIN_AC                     1128
#define IDC_MAGIC_RESISTANCE            1131
#define IDC_SPIN_MAGIC_RESISTANCE       1132
#define IDS_SINGLESAVEDIR               2000
#define IDS_MULTISAVEDIR                2001
#define IDS_CHARACTERDIR                2002
#define ID_SETTINGS_GAMELOCATION        32771
#define ID_FILE_OPEN_CHR                32772
#define ID_HELP_VIEWREADMETXT           32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
