// stdafx.cpp : source file that includes just the standard includes
//	BGEdit.pch will be the pre-compiled header
//	stdafx.obj will contain the pre-compiled type information

#include "stdafx.h"

// Path to Baldur's Gate installation.
CString _strGamePath;

// Remove the menu item that allows opening of .chr files when FALSE.
BOOL _bAllowChrEdit = FALSE;

ITEMTYPE _itemType[] = 
{
	"Armor",
	"Weapon",
	"Helm",
	"Amulet",
	"Missile",
	"Belt",
	"Ring",
	"Shield",
	"Boot",
	"Cloak",
	"Gauntlet",
	"Potion",
	"Wand",
	"Book",
	"Scroll",
	"Misc",
	"???",
	NULL
};

// This needs to match the number from NPC_ITEMSLOTS.
ITEMPOS _itemPos[NUM_ITEM_SLOTS] = 
{
	"Helm",
	"Armor",
	"Shield",
	"Gauntlet",
	"Ring",
	"Ring",
	"Amulet",
	"Belt",
	"Boots",
	"Weap 1",
	"Weap 2",
	"Weap 3",
	"Weap 4",
	"Quiv 1",
	"Quiv 2",
	"Quiv 3",
	"Unused",
	"Cloak",
	"Quick 1",
	"Quick 2",
	"Quick 3",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv",
	"Inv"
};

KNOWNITEM _items[] =
{
	{TYPE_HELM,"HELM","01","Helmet",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","02","Helmet of Opposite Alignment",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","03","Helm of Glory",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","04","Helmet of Defense",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","05","Helmet of Infravision",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","06","Helmet of Charm Protection",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","07","Helm of Balduran",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","08","Helmet",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","09","Helmet",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","10","Helmet",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","11","Helmet",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","12","Helmet",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","13","Helmet",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","14","Helmet of ???",0,FALSE,TRUE},
	{TYPE_HELM,"HELM","15","Kiel's Helmet",0,FALSE,TRUE},

	{TYPE_BELT,"BELT","01","Girdle",0,FALSE,TRUE},
	{TYPE_BELT,"BELT","02","Golden Girdle",0,FALSE,TRUE},
	{TYPE_BELT,"BELT","03","Girdle of Bluntness",0,FALSE,TRUE},
	{TYPE_BELT,"BELT","04","Girdle of Piercing",0,FALSE,TRUE},
	{TYPE_BELT,"BELT","05","Girdle of Masculinity/Femininity",0,FALSE,TRUE},

	{TYPE_BOOT,"BOOT","01","Boots of Speed",0,FALSE,TRUE},
	{TYPE_BOOT,"BOOT","02","Boots of Stealth",0,FALSE,TRUE},
	{TYPE_BOOT,"BOOT","03","Boots of the North",0,FALSE,TRUE},
	{TYPE_BOOT,"BOOT","04","Boots of Avoidance",0,FALSE,TRUE},
	{TYPE_BOOT,"BOOT","05","Boots of Grounding",0,FALSE,TRUE},
	{TYPE_BOOT,"BOOT","06","Worn out Boots",0,FALSE,TRUE},
	
	{TYPE_GLOVE,"BRAC","01","Bracers of Defense AC8",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","02","Bracers of Defense AC7",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","03","Bracers of Defense AC6",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","04","Bracers of Archery",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","05","Bracers",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","06","Gauntlets of Ogre Power",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","07","Gauntlets of Dexterity",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","08","Gauntlets of Fumbling",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","09","Gauntlets of Weapon Skill",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","10","Gauntlets of Weapon Expertise",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","11","Gauntlets of ???",0,FALSE,TRUE},
	{TYPE_GLOVE,"BRAC","12","Bracers of Bonding",0,FALSE,TRUE},

	{TYPE_ARMOR,"PLAT","01","Plate Mail",0,FALSE,TRUE},
	{TYPE_ARMOR,"PLAT","02","Plate Mail +1",0,FALSE,TRUE},
	{TYPE_ARMOR,"PLAT","04","Full Plate Mail",0,FALSE,TRUE},
	{TYPE_ARMOR,"PLAT","05","Full Plate Mail +1",0,FALSE,TRUE},
	{TYPE_ARMOR,"PLAT","06","Ankheg Plate Mail",0,FALSE,TRUE},
	{TYPE_ARMOR,"PLAT","07","Plate Mail",0,FALSE,TRUE},
	{TYPE_ARMOR,"PLAT","08","Plate Mail +3",0,FALSE,TRUE},
	{TYPE_ARMOR,"CHAN","01","Chainmail",0,FALSE,TRUE},
	{TYPE_ARMOR,"CHAN","02","Chainmail +1",0,FALSE,TRUE},
	{TYPE_ARMOR,"CHAN","03","Chainmail +2",0,FALSE,TRUE},
	{TYPE_ARMOR,"CHAN","04","Splint Mail",0,FALSE,TRUE},
	{TYPE_ARMOR,"CHAN","05","Splint Mail +1",0,FALSE,TRUE},
	{TYPE_ARMOR,"CHAN","06","Mithril Chain Mail +4",0,FALSE,TRUE},
	{TYPE_ARMOR,"CHAN","07","Chainmail +3",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","01","Leather Armor",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","02","Leather Armor +1",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","03","Leather Armor +2",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","04","Studded Leather Armor",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","05","Studded Leather Armor +1",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","06","Studded Leather Armor +2 Missile Attraction",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","07","Studded Leather Armor +2",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","08","Shadow Armor",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","09","Leather Armor +3",0,FALSE,TRUE},
	{TYPE_ARMOR,"LEAT","10","Hide Armor",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","09","Mage Robe of Cold Resistance",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","10","Mage Robe of Fire Resistance",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","11","Mage Robe of Electrical Resistance",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","12","Knave's Robe",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","13","Traveller's Robe",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","14","Adventurer's Robe",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","15","Robe of the Good Archmagi",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","16","Robe of the Neutral Archmagi",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","17","Robe of the Evil Archmagi",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","18","Knave's Robe",0,FALSE,TRUE},
	{TYPE_ARMOR,"CLCK","19","Robe of the Good Archmagi",0,FALSE,TRUE},

	{TYPE_CLOAK,"CLCK","01","Cloak of Protection +1",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","02","Cloak of Protection +2",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","03","Cloak of Displacement",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","04","Cloak of the Wolf",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","05","Cloak of Balduran",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","06","Cloak of Non-Detection",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","07","Nymph Cloak",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","08","Algernon's Cloak",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","20","Cloak of the Shield",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","21","Holy Cloak",0,FALSE,TRUE},
	{TYPE_CLOAK,"CLCK","22","Shandalar's Cloak",0,FALSE,TRUE},

	{TYPE_SHIELD,"SHLD","01","Small Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","02","Small Shield +1",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","03","Medium Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","04","Medium Shield +1",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","05","Large Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","06","Large Shield +1",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","07","Large Shield +1, +4 vs Missiles",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","08","Buckler",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","09","Buckler",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","10","Buckler",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","11","Small Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","12","Small Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","13","Medium Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","14","Medium Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","15","Large Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","16","Large Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","18","Large Shield",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","19","Large Shield +2",0,FALSE,TRUE},
	{TYPE_SHIELD,"SHLD","20","Kiel's Buckler",0,FALSE,TRUE},

	{TYPE_WEAPON,"HAMM","01","War Hammer",0,FALSE,TRUE},
	{TYPE_WEAPON,"HAMM","02","War Hammer +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"HAMM","03","War Hammer +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"HAMM","04","War Hammer +1, +4 vs Giants",0,FALSE,TRUE},
	{TYPE_WEAPON,"DART","01","Dart",0,TRUE,TRUE},
	{TYPE_WEAPON,"DART","02","Dart +1",0,TRUE,TRUE},
	{TYPE_WEAPON,"DART","03","Dart of Stunning",0,TRUE,TRUE},
	{TYPE_WEAPON,"DART","04","Dart of Wounding",0,TRUE,TRUE},
	{TYPE_WEAPON,"SPER","01","Spear",0,FALSE,TRUE},
	{TYPE_WEAPON,"SPER","02","Spear +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"SPER","03","Spear +3, Backbiter",0,FALSE,TRUE},
	{TYPE_WEAPON,"SPER","04","Spear +3",0,FALSE,TRUE},
	{TYPE_WEAPON,"STAF","01","Quarter Staff",0,FALSE,TRUE},
	{TYPE_WEAPON,"STAF","02","Quarter Staff +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"STAF","03","Quarter Staff",0,FALSE,TRUE},
	{TYPE_WEAPON,"STAF","04","Quarter Staff",0,FALSE,TRUE},
	{TYPE_WEAPON,"STAF","05","Staff of Striking",0,TRUE,TRUE},
	{TYPE_WEAPON,"STAF","06","Staff Mace +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"STAF","07","Staff Spear +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"STAF","08","Quarter Staff +3",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","01","Dagger",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","02","Dagger +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","03","Dagger +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","04","Dagger +2, Longtooth",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","05","Throwing Dagger",0,TRUE,TRUE},
	{TYPE_WEAPON,"DAGG","06","Nester's Dagger",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","07","Kylee's Dagger",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","08","Hentold's Dagger",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","09","Silver Dagger, Werebane",0,FALSE,TRUE},
	{TYPE_WEAPON,"DAGG","10","Soultaker Dagger",0,FALSE,TRUE},
	{TYPE_WEAPON,"SLNG","01","Sling",0,FALSE,TRUE},
	{TYPE_WEAPON,"SLNG","02","Sling +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"SLNG","03","Sling +3",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","01","Bastard Sword",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","02","Bastard Sword +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","03","Bastard Sword +1, +3 vs Shapeshifters",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","04","Long Sword",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","05","Long Sword +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","06","Long Sword +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","07","Short Sword",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","08","Short Sword +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","09","Short Sword +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","10","Short Sword of Backstabbing",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","11","Flaming Sword (no ID description)",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","12","Hull's Longsword",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","13","Moonblade",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","14","Short Sword +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","15","Scimitar +3, Frostbrand",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","16","Scimitar +5, Defender",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","17","Perdue's Short Sword",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","18","Sword of Balduran",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","19","Vampire's Revenge",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","20","Scimitar",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","21","Short Sword",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","22","Scimitar +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","23","Scimitar +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","24","Longsword +1, Flametongue",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW1H","99","Sword of Chaos",0,TRUE,TRUE},
	{TYPE_WEAPON,"SW2H","01","Two Handed Sword",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW2H","02","Two Handed Sword +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW2H","03","Two Handed Sword, Cursed Berserking +3",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW2H","05","Two Handed Sword",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW2H","06","Spider's Bane",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW2H","07","Two Handed Sword +3",0,FALSE,TRUE},
	{TYPE_WEAPON,"SW2H","08","Durlag's Pride",0,FALSE,TRUE},
	{TYPE_WEAPON,"AX1H","01","Battle Axe",0,FALSE,TRUE},
	{TYPE_WEAPON,"AX1H","02","Battle Axe +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"AX1H","03","Battle Axe +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"AX1H","04","Throwing Axe",0,FALSE,TRUE},
	{TYPE_WEAPON,"AX1H","05","Throwing Axe +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"AX1H","06","Throwing Axe +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"AX1H","07","Bala's Axe",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","01","Club",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","02","Flail",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","03","Flail +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","04","Mace",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","05","Mace +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","06","Morning Star",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","07","Morning Star +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","08","Flail",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","09","Kiel's Morning Star",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","10","Club +1, +3 vs Unnatural",0,FALSE,TRUE},
	{TYPE_WEAPON,"BLUN","11","Mace +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"HALB","01","Halberd",0,FALSE,TRUE},
	{TYPE_WEAPON,"HALB","02","Halberd +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"HALB","03","Halberd +2",0,FALSE,TRUE},
	{TYPE_WEAPON,"XBOW","01","Heavy Crossbow",0,FALSE,TRUE},
	{TYPE_WEAPON,"XBOW","02","Heavy Crossbow +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"XBOW","03","Heavy Crossbow of Accuracy",0,FALSE,TRUE},
	{TYPE_WEAPON,"XBOW","04","Light Crossbow",0,FALSE,TRUE},
	{TYPE_WEAPON,"XBOW","05","Light Crossbow +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"XBOW","06","Light Crossbow of Speed",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","01","Composit Long Bow",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","02","Composit Long Bow +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","03","Long Bow",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","04","Long Bow +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","05","Short Bow",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","06","Short Bow +1",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","07","Long Bow of Marksmanship",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","08","Eagle Bow",0,FALSE,TRUE},
	{TYPE_WEAPON,"BOW","09","Long Bow",0,FALSE,TRUE},

	{TYPE_WAND,"WAND","02","Wand of Fear",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","03","Wand of Magic Missiles",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","04","Wand of Paralyzation",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","05","Wand of Fire",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","06","Wand of Frost",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","07","Wand of Lightning",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","08","Wand of Sleep",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","09","Wand of Polymorphing",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","10","Wand of Monster Summoning",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","11","Wand of the Heavens",0,TRUE,TRUE},
	{TYPE_WAND,"WAND","12","Wand of Magic Missiles",0,TRUE,TRUE},

	{TYPE_MISSILE,"BOLT","01","Bolt",0,TRUE,TRUE},
	{TYPE_MISSILE,"BOLT","02","Bolt +1",0,TRUE,TRUE},
	{TYPE_MISSILE,"BOLT","03","Bolt of Lightning",0,TRUE,TRUE},
	{TYPE_MISSILE,"BOLT","04","Bolt of Biting",0,TRUE,TRUE},
	{TYPE_MISSILE,"BOLT","05","Bolt of Polymorphing",0,TRUE,TRUE},
	{TYPE_MISSILE,"BOLT","06","Bolt +2",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","01","Arrow",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","02","Arrow +1",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","03","Arrow of Slaying",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","04","Acid Arrow",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","05","Arrow of Biting",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","06","Arrow of Detonation",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","07","Arrow of Dispelling",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","08","Arrow of Fire",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","09","Arrow of Ice",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","10","Arrow of Piercing",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","11","Arrow +2",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","12","Arrow of Biting",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","14","Poisoned Arrow",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","15","Arrow of Ice",0,TRUE,TRUE},
	{TYPE_MISSILE,"AROW","16","Arrow of Ice",0,TRUE,TRUE},
	{TYPE_MISSILE,"BULL","01","Bullet",0,TRUE,TRUE},
	{TYPE_MISSILE,"BULL","02","Bullet +1",0,TRUE,TRUE},
	{TYPE_MISSILE,"BULL","03","Bullet +2",0,TRUE,TRUE},

	{TYPE_RING,"RING","01","Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","02","Ring of Fire Resistance",0,FALSE,TRUE},
	{TYPE_RING,"RING","03","Ring of Animal Friendship",0,FALSE,TRUE},
	{TYPE_RING,"RING","04","Ring of Clumsiness",0,FALSE,TRUE},
	{TYPE_RING,"RING","05","Ring of Invisibility",0,FALSE,TRUE},
	{TYPE_RING,"RING","06","Ring of Protection +1",0,FALSE,TRUE},
	{TYPE_RING,"RING","07","Ring of Protection +2",0,FALSE,TRUE},
	{TYPE_RING,"RING","08","Ring of Wizardry",0,FALSE,TRUE},
	{TYPE_RING,"RING","09","Ring of Free Action",0,FALSE,TRUE},
	{TYPE_RING,"RING","10","Gold Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","11","Silver Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","12","Onyx Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","13","Jade Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","14","Greenstone Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","15","Bloodstone Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","16","Angel Skin Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","17","Flamedance Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","18","Fire Opal Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","19","Ruby Ring",0,FALSE,TRUE},
	{TYPE_RING,"RING","20","Ring of Energy",0,TRUE,TRUE},
	{TYPE_RING,"RING","21","Ring of Infravision",0,FALSE,TRUE},
	{TYPE_RING,"RING","22","Ring of Holiness",0,FALSE,TRUE},
	{TYPE_RING,"RING","23","Ring of Folly",0,FALSE,TRUE},
	{TYPE_RING,"RING","25","Kovera's Ring of Protection",0,FALSE,TRUE},

	{TYPE_POTION,"POTN","02","Potion of Fire Resistance",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","03","Potion of Hill Giant Strength",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","04","Potion of Frost Giant Strength",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","05","Potion of Fire Giant Strength",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","06","Potion of Cloud Giant Strength",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","07","Potion of Storm Giant Strength",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","08","Potion of Healing",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","09","Potion of Heroism",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","10","Potion of Invisibility",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","11","Potion of Invulnerability",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","12","Potion of Stone Giant Strength",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","13","Oil of Fiery Burning",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","14","Oil of Speed",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","15","Red Potion",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","16","Violet Potion",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","17","Elixir of Health",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","18","Potion of Absorbtion",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","19","Potion of Agility",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","20","Anitdote",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","21","Potion of Clarity",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","22","Potion of Cold Resistance",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","23","Oil of Speed",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","24","Potion of Defense",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","25","Potion of Healing",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","26","Potion of Explosions",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","27","Potion of Firebreath",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","28","Potion of Fortitude",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","29","Potion of Genius",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","30","Potion of Infravision",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","31","Potion of Insulation",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","32","Antidote",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","33","Potion of Magic Blocking",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","34","Potion of Magic Protection",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","35","Potion of Magic Shielding",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","36","Potion of Master Thievery",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","37","Potion of Mind Focusing",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","38","Potion of Mirrored Eyes",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","39","Potion of Perception",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","40","Potion of Invulnerability",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","41","Potion of Power",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","42","Potion of Regeneration",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","43","Potion of Insight",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","44","Potion of Strength",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","45","Potion of Freedom",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","46","Potion of Stone Form",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","47","Marek's Potion of Antidote",0,TRUE,TRUE},
	{TYPE_POTION,"POTN","48","Vial of Mysterious Liquid",0,TRUE,TRUE},

	{TYPE_AMULET,"AMUL","01","Necklace of Missiles",0,TRUE,TRUE},
	{TYPE_AMULET,"AMUL","02","Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","04","Studded Necklace with Zios Gems",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","05","Bluestone Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","06","Agni Mani Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","07","Rainbow Obsidian Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","08","Tiger Cowrie Shell Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","09","Silver Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","10","Gold Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","11","Pearl Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","12","Laeral's Tear Necklace",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","13","Bloodstone Amulet",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","14","Amulet of Protection +1",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","15","Shield Amulet",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","16","Amulet of Metaspell Influence",0,FALSE,TRUE},
	{TYPE_AMULET,"AMUL","17","Greenstone Amulet",0,TRUE,TRUE},
	{TYPE_AMULET,"AMUL","18","Wolfbane Charm",0,FALSE,TRUE},

	{TYPE_BOOK,"BOOK","01","Magical Book",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","02","Spell Book",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","03","Manual of Bodily Health",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","04","Manual of Gainful Exercise",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","05","Manual of Quickness of Action",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","06","Tome of Clear Thought",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","07","Tome of Leadership and Influence",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","08","Tome of Understanding",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","09","Normal Book",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","10","History of Calimsham",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","11","History of Cormyr",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","12","History of Dambrath",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","13","History of Durpar and Var the Golden",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","14","History of Estagund",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","15","History of Gondegal the Lost King",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","16","History of Halruaa",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","17","History of Luiren",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","18","History of Sembia",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","19","History of Shadowdale - Fall of Azmaer",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","20","History of Shadowdale - First Lord",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","21","History of Shadowdale - Massacre",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","22","History of Shadowdale - Aumry",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","23","History of Shadowdale - False Lord",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","24","History of Shadowdale - Khelben Kills",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","25","History of Shadowdale - Lords Accepted",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","26","History of Shadowdale - No Lords",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","27","History of Shadowdale - Doust Sulwood",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","28","History of Shadowdale - Elminster Moves In",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","29","History of Shadowdale - Successor",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","30","History of Shadowdale - Shaerl and Mourngrym",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","31","History of Shadowdale - Mourngrym's Rule",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","32","History of Tethyr",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","33","History of the Bell in the Depths",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","34","History of Chose of Mystra",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","35","History of the Dales and the Elven Court",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","36","History of the Dead Three",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","37","History of the Dragon Coast",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","38","History of the Drow - The Descent",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","39","History of the Drow - Dark Wars",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","40","History of the Fateful Coin",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","41","History of the Last March of the Giants",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","42","History of the Moonsea",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","43","History of the North - First Flowering",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","44","History of the North - Crown Wars",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","45","History of the North - Recent",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","46","History of the North - Elven Exodus",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","47","History of the North - Plague of Humans",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","48","History of the North - Might of Men",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","49","History of the North - Year of the Banner",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","50","History of the North - Year of the Gauntlet",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","51","History of the North - Return of the Beast",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","52","History of the North - Year of the Tankard",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","53","History of the Red Ravens",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","54","History of the Sisters of Light and Darkness",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","55","History of the Unicorn Run",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","56","History of the Valley of the Gods",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","57","History of the Vast",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","58","History of the Western Heartlands",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","59","History of the Zhentarim",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","60","History of the Ulgarth",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","61","History of Amn",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","62","History of Waterdeep",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","63","History of Waterdeep - Pioneers",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","64","History of Waterdeep - Warlords",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","65","History of Waterdeep - Bloody Reign",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","66","History of Waterdeep - Da Lords",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","67","History of Waterdeep - Return of the Lords",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","68","History of the Nether Scrolls",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","70","Yago's Book of Curses",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","71","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","72","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","73","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","74","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","75","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","76","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","77","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","78","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","79","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","80","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","81","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","82","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","83","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","84","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","85","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","86","Dusty Book (1)",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","87","Balduran's Log Book",0,FALSE,TRUE},
	{TYPE_BOOK,"BOOK","88","Recipes and Ruminations of One Dradeel of Tethir",0,FALSE,TRUE},

	{TYPE_MISC,"MISC","01","Winter Wolf Pelt",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","04","Basilus' Holy Symbol",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","07","Gold",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","12","Ankheg Shell",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","13","Body of Samuel",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","16","Fire Agate Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","17","Lynx Eye Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","18","Sunstone Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","19","Tuquoise Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","20","Bloodstone Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","21","Skydrop Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","22","Andar Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","23","Jasper Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","24","Tchazar Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","25","Zircon Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","26","Iol Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","27","Moonstone Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","28","Waterstar Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","29","Ziose Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","30","Chrysoberyl Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","31","Star Diopside Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","32","Shandon Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","33","Aquamarine Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","34","Garnet Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","35","Horn Coral",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","36","Pearl",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","37","Sphene Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","38","Black Opal",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","39","Water Opal",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","40","Moonbar Gem",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","41","Star Saphire",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","42","Diamond",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","43","Emerald",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","44","King's Tears",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","45","Rogue Stone",0,TRUE,TRUE},
	{TYPE_MISC,"MISC","47","Golden Pantaloons",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","48","Idol",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","49","Melicamp the Chicken",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","50","Skull",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","51","Lock of Nymph's Hair",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","52","Wyvern Head",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","53","Bowl of Water Elemental Control",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","54","Child's Body",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","55","Duke Eltan's Body",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","56","Broken Weapon",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","57","Broken Shield",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","58","Broken Armor",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","59","Broken Miscellaneous",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","60","Spider Body",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","61","Bottle of Wine",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","62","Dead Cat",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","63","Chew Toy",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","64","Telescope",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","65","Brage's Body",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","66","Farmer Brun's Son (Dead)",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","67","Brun's Dead Son",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","68","Abela the Nymph",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","69","Helshara's Artifact Fragment",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","70","Delorna's Statue",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","71","Delorna's Spellbook",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","72","The Claw of Kazgaroth",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","73","The Horn of Kazgaroth",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","74","The Candle",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","75","Dagger of Venom",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","76","The Dream Potion",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","77","Skull of Kereph",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","78","Inauguration Invitation",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","79","Female Body",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","80","Male Body",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","81","Skull of Kereph",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","82","Ancient Armor",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","83","Key to River Plug",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","84","Boo (he's so cute!)",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","85","Mulahey's Holy Symbol",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","86","Bandit Scalp",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","87","Contaminated Iron",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","88","Rabbit's Foot",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","89","Edwin's Amulet",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","90","Chelak's Body",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","91","Grapes",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","92","Switch for an Engine",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","93","Odd Looking Key",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","94","Mallet Head",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","95","Mallet Handle",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","96","Peladan",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","97","De'Tranion's Baalor Ale",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","98","Durlag's Goblet",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","99","Cursed Plate Mail Armor and Spear",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1A","Bottle of Wine",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1B","Butter Knife of Balduran",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1C","Sea Charts",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1E","Evan's Body",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1F","Dradeel's Spellbook",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1G","Farthing's Dolly",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1H","Gong Mallet",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1I","Belladonna Flower",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","1J","Glittering Beljuril Gemstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2B","Level 1 Exit Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2C","Islanne Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2D","Kiel Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2E","Fuernebol Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2F","Teleportation Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2G","Level 2 Exit Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2H","Shandalar’s Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2I","Wardstone Forgery",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2J","Wardstone Forgery",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2K","Compass Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2L","Bone Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2M","Dwarven Rune Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2N","Dwarven Rune Wardstone",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2O","Lock of Hair from Kirinhale",0,FALSE,TRUE},
	{TYPE_MISC,"MISC","2P","Greagan’s Harp",0,FALSE,TRUE},

	{TYPE_SCROLL,"SCRL","02","Spell Scroll",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","03","Protection from Acid",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","04","Protection from Acid",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","05","Protection from Electricity",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","06","Protection from Fire",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","07","Protection from Magic",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","08","Protection from Poison",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","09","Protection from Undead",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","10","Cursed Scroll of Weakness",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","11","Cursed Scroll of Clumsiness",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","12","Cursed Scroll of Foolishness",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","13","Cursed Scroll of Ugliness",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","14","Cursed Scroll of Summon Monster",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","15","Protection from Petrification",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","16","Cursed Scroll of Petrification",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","17","Cursed Scroll of Ailment",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","18","Cursed Scroll of Stupidity",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","56","Cure Serious Wounds",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","58","Free Action",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","59","Neutralize Poison",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","61","Cure Critical Wounds",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","62","Flame Strike",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","63","Raise Dead",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","66","Grease",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","67","Armor",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","68","Burning Hands",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","69","Charm Person",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","70","Color Spray",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","71","Blindness",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","72","Friends",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","73","Protection from Petrification",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","75","Identify",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","76","Infravision",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","77","Magic Missile",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","78","Protection from Evil",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","79","Shield",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","80","Shocking Grasp",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","81","Sleep",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","82","Chill Touch",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","83","Chromatic Orb",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","84","Larloch's Minor Drain",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","85","Blur",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","86","Detect Evil",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","87","Detect Invisibility",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","89","Horror",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","90","Invisibility",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","91","Knock",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","92","Known Alignment",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","93","Luck",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","94","Resist Fear",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","95","Melf's Acid Arrow",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","96","Mirror Image",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","97","Stinking Cloud",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","98","Strength",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","99","Web",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1B","Agannazar's Scorcher",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1C","Ghoul Touch",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1D","Clairvoyance",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1E","Dispel Magic",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1F","Flame Arrow",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1G","Fireball",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1H","Haste",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1I","Hold Person",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1K","Lightning Bolt",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1L","Monster Summoning 1",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1M","Non-Detection",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1N","Protection from Normal Missiles",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1O","Slow",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1P","Skull Trap",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1Q","Vampiric Touch",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1R","Wraith Form",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1S","Dire Charm",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1T","Ghost Armor",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1U","Confusion",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1V","Dimension Door",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1Y","Improved Invisibility",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","1Z","Minor Globe of Invulnerability",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","2A","Monster Summoning 2",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","2D","Animate Dead",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","2E","Cloudkill",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","2F","Cone of Cold",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","2G","Monster Summoning 3",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","2H","Shadow Door",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","2I","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2J","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2K","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2L","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2M","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2N","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2O","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2P","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2Q","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2R","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2S","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2T","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2U","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2V","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2W","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2X","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2Y","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","2Z","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","3A","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","3B","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","3C","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","3D","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","3E","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","3F","The Diary of Sarevok",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","3G","Vocalize",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","3H","Protection from Evil",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","3I","Letter",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","3Z","Gorion's Scroll",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","ZZ","Summon Cow",0,FALSE,TRUE},
	{TYPE_SCROLL,"SCRL","5A","Mental Domination",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5B","Defensive Harmony",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5C","Protection from Lightning",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5D","Protection from Evil 10ft",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5E","Champion's Strength",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5F","Chaotic Commands",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5G","Remove Curse",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5H","Emotion, Hopelessness",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5I","Greater Malison",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5J","Otiluke's Resilient Sphere",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5K","Spirit Armor",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5L","Polymorph Other",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5M","Polymorph Self",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5N","Domination",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5O","Hold Monster",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5P","Chaos",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5Q","Feeblemind",0,TRUE,TRUE},
	{TYPE_SCROLL,"SCRL","5R","Andris' Journal",0,FALSE,TRUE},

	{TYPE_ENDOFLIST,"","","",0,FALSE,FALSE}
};

SPELLDESC _spells[] = 
{
	{ST_INNATE,"SPIN101","Cure Light Wounds"},
	{ST_INNATE,"SPIN102","Slow Poison"},
	{ST_INNATE,"SPIN103","Draw Upon Holy Might"},
	{ST_INNATE,"SPIN104","Larloch's Minor Drain"},
	{ST_INNATE,"SPIN105","Ghoul Touch"},
	{ST_INNATE,"SPIN106","Vampiric Touch"},
	{ST_INNATE,"SPIN107","Shapeshift Brown Bear"},
	{ST_INNATE,"SPIN108","Charm Animal"},
	{ST_INNATE,"SPIN109","Lay on Hands"},
	{ST_INNATE,"SPIN110","Shapeshift Wolf"},
	{ST_INNATE,"SPIN111","Shapeshift Black Bear"},
	{ST_INNATE,"SPIN112","Dispel Magic"},
	{ST_INNATE,"SPIN113","Spiritual Hammer"},
	{ST_INNATE,"SPIN114","Summon Dread Wolf"},
	{ST_INNATE,"SPIN115","Summon Ghast"},
	{ST_INNATE,"SPIN116","Create Poisoned Arrows"},
	{ST_INNATE,"SPIN117","Berserk"},
	{ST_INNATE,"SPIN118","Invisibility"},
	{ST_INNATE,"SPIN119","Charm Person"},
	{ST_INNATE,"SPIN120","Detect Evil"},
	{ST_INNATE,"SPIN121","Protection from Evil"},
	{ST_INNATE,"SPIN122","Shapeshift Natural Form"},
	{ST_INNATE,"SPIN123","Shapeshift Natural Form"},
	{ST_INNATE,"SPIN124","Shapeshift Natural Form"},

	{ST_PRIEST,"SPPR101","Bless"},
	{ST_PRIEST,"SPPR102","Command Word: Die"},
	{ST_PRIEST,"SPPR103","Cure Light Wounds"},
	{ST_PRIEST,"SPPR104","Detect Evil"},
	{ST_PRIEST,"SPPR105","Entangle"},
	{ST_PRIEST,"SPPR106","Magic Stone"},
	{ST_PRIEST,"SPPR107","Protection from Evil"},
	{ST_PRIEST,"SPPR108","Remove Fear"},
	{ST_PRIEST,"SPPR109","Sanctuary"},
	{ST_PRIEST,"SPPR110","Shillelagh"},
	{ST_PRIEST,"SPPR201","Aid"},
	{ST_PRIEST,"SPPR202","Barkskin"},
	{ST_PRIEST,"SPPR203","Chant"},
	{ST_PRIEST,"SPPR204","Charm Person or Mammal"},
	{ST_PRIEST,"SPPR205","Find Traps"},
	{ST_PRIEST,"SPPR206","Flame Blade"},
	{ST_PRIEST,"SPPR207","Good Berries"},
	{ST_PRIEST,"SPPR208","Hold Person"},
	{ST_PRIEST,"SPPR209","Know Alignment"},
	{ST_PRIEST,"SPPR210","Resist Fire/Cold"},
	{ST_PRIEST,"SPPR211","Silence 15' Radius"},
	{ST_PRIEST,"SPPR212","Slow Poison"},
	{ST_PRIEST,"SPPR213","Spiritual Hammer"},
	{ST_PRIEST,"SPPR214","Draw Upon Holy Might"},
	{ST_PRIEST,"SPPR301","Animate Dead"},
	{ST_PRIEST,"SPPR302","Call Lightning"},
	{ST_PRIEST,"SPPR303","Dispel Magic"},
	{ST_PRIEST,"SPPR304","Glyph of Warding"},
	{ST_PRIEST,"SPPR305","Hold Animal"},
	{ST_PRIEST,"SPPR306","Protection From Fire"},
	{ST_PRIEST,"SPPR307","Remove Curse"},
	{ST_PRIEST,"SPPR308","Remove Paralysis"},
	{ST_PRIEST,"SPPR309","Invisibility Purge"},
	{ST_PRIEST,"SPPR310","Miscast Magic"},
	{ST_PRIEST,"SPPR311","Rigid Thinking"},
	{ST_PRIEST,"SPPR312","Strength of One"},
	{ST_PRIEST,"SPPR401","Cure Serious Wounds"},
	{ST_PRIEST,"SPPR402","Animal Summoning 1"},
	{ST_PRIEST,"SPPR403","Free Action"},
	{ST_PRIEST,"SPPR404","Neutralize Poison"},
	{ST_PRIEST,"SPPR405","Mental Domination"},
	{ST_PRIEST,"SPPR406","Defensive Harmony"},
	{ST_PRIEST,"SPPR407","Protection from Lightning"},
	{ST_PRIEST,"SPPR408","Protection from Evil 10ft"},
	{ST_PRIEST,"SPPR501","Animal Summoning 2"},
	{ST_PRIEST,"SPPR502","Cure Critical Wounds"},
	{ST_PRIEST,"SPPR503","Flame Strike"},
	{ST_PRIEST,"SPPR504","Raise Dead"},
	{ST_PRIEST,"SPPR507","Champion's Strength"},
	{ST_PRIEST,"SPPR508","Chaotic Commands"},

	{ST_WIZARD,"SPWI101","Grease"},
	{ST_WIZARD,"SPWI102","Armor"},
	{ST_WIZARD,"SPWI103","Burning Hands"},
	{ST_WIZARD,"SPWI104","Charm Person"},
	{ST_WIZARD,"SPWI105","Color Spray"},
	{ST_WIZARD,"SPWI106","Blindness"},
	{ST_WIZARD,"SPWI107","Friends"},
	{ST_WIZARD,"SPWI108","Protection from Petrification"},	 // This is really level 2.
	{ST_WIZARD,"SPWI110","Identify"},
	{ST_WIZARD,"SPWI111","Infravision"},
	{ST_WIZARD,"SPWI112","Magic Missile"},
	{ST_WIZARD,"SPWI113","Protection from Evil"},
	{ST_WIZARD,"SPWI114","Shield"},
	{ST_WIZARD,"SPWI115","Shocking Grasp"},
	{ST_WIZARD,"SPWI116","Sleep"},
	{ST_WIZARD,"SPWI117","Chill Touch"},
	{ST_WIZARD,"SPWI118","Chromatic Orb"},
	{ST_WIZARD,"SPWI119","Larloch's Minor Drain"},
	{ST_WIZARD,"SPWI201","Blur"},
	{ST_WIZARD,"SPWI202","Detect Evil"},
	{ST_WIZARD,"SPWI203","Detect Invisibility"},
	{ST_WIZARD,"SPWI205","Horror"},
	{ST_WIZARD,"SPWI206","Invisibility"},
	{ST_WIZARD,"SPWI207","Knock"},
	{ST_WIZARD,"SPWI208","Know Alignment"},
	{ST_WIZARD,"SPWI209","Luck"},
	{ST_WIZARD,"SPWI210","Resist Fear"},
	{ST_WIZARD,"SPWI211","Melf's Acid Arrow"},
	{ST_WIZARD,"SPWI212","Mirror Image"},
	{ST_WIZARD,"SPWI213","Stinking Cloud"},
	{ST_WIZARD,"SPWI214","Strength"},
	{ST_WIZARD,"SPWI215","Web"},
	{ST_WIZARD,"SPWI217","Agannazar's Sorcher"},
	{ST_WIZARD,"SPWI218","Ghoul Touch"},
	{ST_WIZARD,"SPWI219","Vocalize"},
	{ST_WIZARD,"SPWI299","Summon Cow"},
	{ST_WIZARD,"SPWI301","Clairvoyance"},
	{ST_WIZARD,"SPWI302","Dispel Magic"},
	{ST_WIZARD,"SPWI303","Flame Arrow"},
	{ST_WIZARD,"SPWI304","Fireball"},
	{ST_WIZARD,"SPWI305","Haste"},
	{ST_WIZARD,"SPWI306","Hold Person"},
	{ST_WIZARD,"SPWI308","Lightning Bolt"},
	{ST_WIZARD,"SPWI309","Monster Summoning 1"},
	{ST_WIZARD,"SPWI310","Non-Detection"},
	{ST_WIZARD,"SPWI311","Protection from Normal Missiles"},
	{ST_WIZARD,"SPWI312","Slow"},
	{ST_WIZARD,"SPWI313","Skull Trap"},
	{ST_WIZARD,"SPWI314","Vampiric Touch"},
	{ST_WIZARD,"SPWI315","Wraith Form"},
	{ST_WIZARD,"SPWI316","Dire Charm"},
	{ST_WIZARD,"SPWI318","Ghost Armor"},
	{ST_WIZARD,"SPWI401","Confusion"},
	{ST_WIZARD,"SPWI402","Dimension Door"},
	{ST_WIZARD,"SPWI405","Improved Invisibility"},
	{ST_WIZARD,"SPWI406","Minor Globe of Invulnerability"},
	{ST_WIZARD,"SPWI407","Monster Summoning 2"},
	{ST_WIZARD,"SPWI410","Remove Curse"},
	{ST_WIZARD,"SPWI411","Emotion, Hopelessness"},
	{ST_WIZARD,"SPWI412","Greater Malison"},
	{ST_WIZARD,"SPWI413","Otiluke's Resilient Sphere"},
	{ST_WIZARD,"SPWI414","Spirit Armor"},
	{ST_WIZARD,"SPWI415","Polymorph Other"},
	{ST_WIZARD,"SPWI416","Polymorph Self"},
	{ST_WIZARD,"SPWI501","Animate Dead"},
	{ST_WIZARD,"SPWI502","Cloud Kill"},
	{ST_WIZARD,"SPWI503","Cone of Cold"},
	{ST_WIZARD,"SPWI504","Monster Summoning 3"},
	{ST_WIZARD,"SPWI505","Shadow Door"},
	{ST_WIZARD,"SPWI506","Domination"},
	{ST_WIZARD,"SPWI507","Hold Monster"},
	{ST_WIZARD,"SPWI508","Chaos"},
	{ST_WIZARD,"SPWI509","Feeblemind"},

	{ST_ENDOFLIST,"","Unknown"}
};

RACE _race[] = 
{
	{"Human",RACE_HUMAN},
	{"Elf",RACE_ELF},
	{"Half-Elf",RACE_HALFELF},
	{"Dwarf",RACE_DWARF},
	{"Halfling",RACE_HALFLING},
	{"Gnome",RACE_GNOME},
	{NULL,0},
};

SEX _sex[] =
{
	{"Male",SEX_MALE},
	{"Female",SEX_FEMALE},
	{"Other",SEX_OTHER},
	{NULL,0}
};

CLASS _class[] =
{
	{"Mage",CLASS_MAGE},
	{"Fighter",CLASS_FIGHTER},
	{"Cleric",CLASS_CLERIC},
	{"Thief",CLASS_THIEF},
	{"Bard",CLASS_BARD},
	{"Paladin",CLASS_PALADIN},
	{"Fighter/Mage",CLASS_FIGHTERMAGE},
	{"Fighter/Cleric",CLASS_FIGHTERCLERIC},
	{"Fighter/Thief",CLASS_FIGHTERTHIEF},
	{"Fighter/Mage/Thief",CLASS_FIGHTERMAGETHIEF},
	{"Druid",CLASS_DRUID},
	{"Ranger",CLASS_RANGER},
	{"Mage/Thief",CLASS_MAGETHIEF},
	{"Cleric/Mage",CLASS_CLERICMAGE},
	{"Cleric/Thief",CLASS_CLERICTHIEF},
	{"Fighter/Druid",CLASS_FIGHTERDRUID},
	{"Fighter/Mage/Cleric",CLASS_FIGHTERMAGECLERIC},
	{"Cleric/Ranger",CLASS_CLERICRANGER},
	{NULL,0}
};

ALIGNMENT _alignment[] =
{
	{"Lawful Good",ALIGN_LAWFULGOOD},
	{"Neutral Good",ALIGN_NEUTRALGOOD},
	{"Chaotic Good",ALIGN_CHAOTICGOOD},
	{"Lawful Neutral",ALIGN_LAWFULNEUTRAL},
	{"True Neutral",ALIGN_TRUENEUTRAL},
	{"Chaotic Neutral",ALIGN_CHAOTICNEUTRAL},
	{"Lawful Evil",ALIGN_LAWFULEVIL},
	{"Neutral Evil",ALIGN_NEUTRALEVIL},
	{"Chaotic Evil",ALIGN_CHAOTICEVIL},
	{NULL,0}
};

MAGESPECIALTY _mageSpecialty[] = 
{
	{"Abjurer",MAGE_ABJURER},
	{"Conjurer",MAGE_CONJURER},
	{"Diviner",MAGE_DIVINER},
	{"Enchanter",MAGE_ENCHANTER},
	{"Illusionist",MAGE_ILLUSIONIST},
	{"Invoker",MAGE_INVOKER},
	{"Necromancer",MAGE_NECROMANCER},
	{"Transmuter",MAGE_TRANSMUTER},
	{"No Specialty",MAGE_MAGE},
	{NULL,0},
};

// The RACE_ defines from the data file are used to index this.
THIEFRACEMOD _thiefRaceMod[NUM_THIEFRACEMOD] =
{
	{0,0,0,0},		// Nothing
	{0,0,0,0},		// Human
	{5,-5,0,10},	// Elf
	{10,0,0,5},		// Half Elf
	{0,10,15,0},	// Dwarf
	{5,5,5,15},		// Halfling
	{0,5,10,5},		// Gnome
};

// The index for this is character dex-1. Dex from 1 = 25 are supported (0-24)
THIEFDEXMOD _thiefDexMod[NUM_THIEFDEXMOD] = 
{
	// Dex 1-9
	{-15,-10,-10,-20},
	{-15,-10,-10,-20},
	{-15,-10,-10,-20},
	{-15,-10,-10,-20},
	{-15,-10,-10,-20},
	{-15,-10,-10,-20},
	{-15,-10,-10,-20},
	{-15,-10,-10,-20},
	{-15,-10,-10,-20},

	// Dex 10-12
	{-10,-5,-10,-15},
	{-5,0,-5,-10},
	{0,0,0,-5},

	// Dex 13-15
	{0,0,0,0},
	{0,0,0,0},
	{0,0,0,0},

	// Dex 16-18
	{0,5,0,0},
	{5,10,0,5},
	{10,15,5,10},

	// Dex 19-21
	{15,20,10,15},
	{20,25,15,18},
	{25,30,20,20},

	// Dex 22-25
	{30,35,25,23},
	{35,40,30,25},
	{40,45,35,30},
	{45,50,40,35}
};

MAPINFO _mapInfo[] =
{
	{"AR0100",TRUE,0,0,"Baldur's Gate, Northwest"},

	{"AR0200",TRUE,0,0,"Baldur's Gate, North Central"},

	{"AR0300",TRUE,0,0,"Baldur's Gate, Northeast"},

	{"AR0400",TRUE,0,0,"Farm, North of Baldur's Gate Bridge"},
	
	{"AR0600",TRUE,0,0,"Baldur's Gate, West"},

	{"AR0700",TRUE,0,0,"Baldur's Gate, Central"},

	{"AR0800",TRUE,0,0,"Baldur's Gate, East"},
		{"AR0800",FALSE,3156,1105,"Lucky Aello's Discount Store"},

	{"AR0900",TRUE,0,0,"Baldur's Gate Bridge"},
		{"AR0900",FALSE,4036,772,"Tenya"},

	{"AR1100",TRUE,0,0,"Baldur's Gate, Southwest"},

	{"AR1200",TRUE,0,0,"Baldur's Gate, South Central"},

	{"AR1300",TRUE,0,0,"Baldur's Gate, Southeast"},

	{"AR1400",TRUE,0,0,"The Farm"},
		{"AR1400",FALSE,3969,467,"Ankhegs"},
		{"AR1400",FALSE,1395,2404,"Entrance to Ankheg Cave"},
		{"AR1400",FALSE,3606,2343,"The Farm"},

	{"AR1600",TRUE,0,0,"West Cloakwood"},
		{"AR1600",FALSE,910,2196,"Amarande's Tower"},
		{"AR1600",FALSE,2112,994,"Baby Wyvern Training Cave"},

	{"AR1700",TRUE,0,0,"North Cloakwood"},
		{"AR1700",FALSE,4339,1759,"Wyvern Caves"},

	{"AR1800",TRUE,0,0,"Cloakwood Mines"},
		{"AR1807",FALSE,202,289,"Mine Entrance"},
		{"AR1801",FALSE,406,277,"Mine Level 1"},
		{"AR1804",FALSE,832,149,"Mine Level 2"},
		{"AR1802",FALSE,724,1241,"Mine Level 3"},
		{"AR1803",FALSE,1412,364,"Mine Level 4"},

	{"AR1900",TRUE,0,0,"Bandit Camp"},
		{"AR1900",FALSE,2160,838,"Gnoll Cave"},
		{"AR1900",FALSE,3632,1235,"Leader's Tent"},

	{"AR2100",TRUE,0,0,"Central Cloakwood"},
		{"AR2100",FALSE,1814,1287,"Entrance to Spider Cave"},

	{"AR2200",TRUE,0,0,"East Cloakwood"},
		{"AR2200",FALSE,2816,2182,"Hunting Lodge"},

	{"AR2300",TRUE,0,0,"Friendly Arms Inn"},
		{"AR2304",FALSE,437,324,"Temple of Wisdom"},
		{"AR2301",FALSE,387,720,"The Inn, First Floor"},
		{"AR2302",FALSE,1036,662,"The Inn, Second Floor"},
		{"AR2303",FALSE,746,810,"The Inn, Third Floor"},

	{"AR2400",TRUE,0,0,"Peldvale"},

	{"AR2600",TRUE,0,0,"Candlekeep"},
		{"AR2600",FALSE,1156,632,"Candlekeep Inn"},
		{"AR2600",FALSE,4643,2668,"Candlekeep Gate"},

	{"AR2700",TRUE,0,0,"Wilderness, East of Candlekeep"},
		{"AR2700",FALSE,3089,1447,"Gorion's Death Site"},

	{"AR2800",TRUE,0,0,"Crossroads: Candlekeep, Beregost, Friendly Arms"},
		{"AR2800",FALSE,1073,1979,"At the crossroads"},
		{"AR2800",FALSE,4705,1763,"Ogre with Girld of Piercing"},

	{"AR2900",TRUE,0,0,"Larswood"},
		{"AR2900",FALSE,4177,829,"Osmadi, Shrine Construction Site"},

	{"AR3000",TRUE,0,0,"Wilderness, East of Larswood"},
		{"AR3000",FALSE,1423,1969,"Red Wizards of Thay"},

	{"AR3100",TRUE,0,0,"Coast, West of High Hedge"},
		{"AR3100",FALSE,1183,1592,"Shipwreck"},

	{"AR3200",TRUE,0,0,"High Hedge"},
		{"AR3200",FALSE,1587,1612,"House"},
		{"AR3200",FALSE,2646,2699,"The Keep"},

	{"AR3300",TRUE,0,0,"Beregost"},
		{"AR3300",FALSE,1671,2897,"Feldpost's Inn"},
		{"AR3300",FALSE,2615,2330,"Burning Wizard"},
		{"AR3300",FALSE,3505,2258,"Red Sheaf"},
		{"AR3300",FALSE,4594,3052,"Thunder Hammer Smithy"},
		{"AR3300",FALSE,3629,3764,"Jovial Juggler"},
		{"AR3300",FALSE,2834,3565,"Spider House"},
		
	{"AR3400",TRUE,0,0,"Temple"},
		{"AR3400",FALSE,1189,1124,"Temple Entrance"},

	{"AR3500",TRUE,0,0,"Wilderness, North of Gullykin"},

	{"AR3600",TRUE,0,0,"Coast, Southwest of High Hedge"},
		{"AR3600",FALSE,306,993,"Golem Cave"},
		{"AR3600",FALSE,949,2880,"Lighthouse"},

	{"AR3700",TRUE,0,0,"Wilderness, South of High Hedge"},
		{"AR3700",FALSE,3627,3081,"Bassilus"},

	{"AR3800",TRUE,0,0,"Wilderness, South of Beregost"},

	{"AR3900",TRUE,0,0,"Ulcaster Ruins"},
		{"AR3900",FALSE,3935,1284,"Icharyd, Skeletal Knight"},
		{"AR3900",FALSE,3146,653,"Dungeon Entrance"},

	{"AR4000",TRUE,0,0,"Gullykin"},
		{"AR4000",FALSE,565,656,"Gullykin Village"},
		{"AR4002",FALSE,325,295,"Dungeon Entrance"},

	{"AR4100",TRUE,0,0,"Coast, South of Lighthouse"},
		{"AR4100",FALSE,2835,1470,"Excavation Site"},
		{"AR4100",FALSE,3390,2153,"Captain Brage"},

	{"AR4200",TRUE,0,0,"Wilderness, Northwestof Nashkel"},

	{"AR4300",TRUE,0,0,"Wilderness, North of Nashkel"},

	{"AR4400",TRUE,0,0,"Wilderness, South of Ulcaster Ruins"},

	{"AR4500",TRUE,0,0,"Firewine Bridge"},
		{"AR4500",FALSE,2785,1663,"Poe"},
		{"AR4500",FALSE,4007,2067,"Dungeon Entrance"},

	{"AR4600",TRUE,0,0,"Coast, North of Gnoll Stronghold"},

	{"AR4700",TRUE,0,0,"Wilderness, West of Nashkel"},

	{"AR4800",TRUE,0,0,"Nashkel"},
		{"AR4800",FALSE,2819,2582,"Belching Dragon Tavern"},
		{"AR4800",FALSE,3281,1813,"Garrison"},
		{"AR4800",FALSE,2671,997,"Temple of Helm"},
		{"AR4800",FALSE,1614,932,"Nashkel Store"},
		{"AR4800",FALSE,1233,757,"Nashkel Inn"},

	{"AR4900",TRUE,0,0,"Carnival"},
	
	{"AR5000",TRUE,0,0,"Wilderness, East of Carnival"},

	{"AR5100",TRUE,0,0,"Gnoll Stronghold"},
		{"AR5100",FALSE,4986,2640,"Entry Area"},
		{"AR5100",FALSE,2324,1188,"Holding Pits"},
		{"AR5100",FALSE,543,2323,"Caves"},

	{"AR5200",TRUE,0,0,"Wilderness, Southwest of Nashkel"},
		{"AR5200",FALSE,1649,3493,"Waterfall"},

	{"AR5300",TRUE,0,0,"Wilderness, South of Nashkel"},

	{"AR5400",TRUE,0,0,"Nashkel Mines"},
		{"AR5400",FALSE,750,2722,"Prism"},
		{"AR5400",FALSE,1291,782,"Mine Entrance"}, 
		{"AR5401",FALSE,1337,572,"Mines, Level 1"}, 
		{"AR5402",FALSE,2314,2501,"Mines, Level 2"}, 
		{"AR5403",FALSE,1562,196,"Mines, Level 3"}, 
		{"AR5404",FALSE,999,1255,"Mines, Level 4"}, 
		{"AR5405",FALSE,199,556,"Mulahey"}, 

	{"AR5500",TRUE,0,0,"Wilderness, East of Nashkel Mines"},

	{NULL,FALSE,0,0,""},
};
